language: android
android:
  components:
    - build-tools-23.0.0
    - android-23
    - extra
     - sys-img-armeabi-v7a-addon-google_apis-google-23

before_script:
# Create and start emulator
- echo no | android create avd --force -n test -t android-23 --abi google_apis/armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- adb wait-for-device
- adb shell input keyevent 82 &
script:
- ./gradlew connectedAndroidTest



